### PR TITLE
Feature powerboard (Issue #51)

### PR DESCRIPTION
**Pull request by calvin-godfrey**

### CODE REVIEW

**Comment by toastertaster** [comment]
I think this is ready to go

**Comment by CarlyAmar** [comment]
Do we want a PDP member or to inherit from PDP? If we inherit, we can also type them better.

**Comment by toastertaster** [comment]
I'm all for good ideas if you have some, but what he's posted is also ready to go to try out.  We can always work towards improvements or different implementations

**Comment by WardBenjamin** [comment]
Yeah, we should definitely try this out with a hardware setup. I don't suggest merging to master until we can verify that it works as intended, so that there is the opportunity to add additional changes to the pull request.

**Pull request merged**
