### PR TITLE
Dev autopickup

### PR DESCRIPTION
**Pull request by WardBenjamin**

### CODE REVIEW

**Comment by CarlyAmar** [comment]
Has some unnecessary changes, remove those and it is a good pull request

**Comment by WardBenjamin** [comment]
Fulfills https://github.com/Chantilly612Code/612-2015/issues/181 with no problems. If you have a problem with this, bring it up with Mr. Baer. There is no possible way that changes made here will break code and you don't want to admit that you are wrong. This is complete, and if you want more changes, then do them yourself. You said to complete a problem, and (finally) gave me some directions. This completes those directions, and does not introduce new problems.

**Comment by CarlyAmar** [comment]
If you can find time to perform a systems test with this code then I will merge.

**Comment by WardBenjamin** [comment]
This has been completed on the kitbot board @ZackAlfakir.

**Comment by CarlyAmar** [comment]
That is not a full systems check. Please reopen when systems check is performed on operational robot.

**Comment by WardBenjamin** [comment]
The kitbot is an operational robot, therefore it is a valid systems check.

**Comment by portpiratech** [comment]
Hi guys... i think we somehow got on your github email list by mistake.
Can you check it out please.

Thanks,
Jim V.
Lead Mentor
Port Piratech FRC Team 4804

**Comment by WardBenjamin** [comment]
@portpiratech I believe it is because you are "watching" the repository. If you visit the github page there should be a button/dropdown menu on the top-right part of the page.
Benjamin Ward, Programmer, FRC Team 612

**Pull request closed without merging**
