### PR TITLE
Implemented MotorSafetyHelper

### PR DESCRIPTION
**Pull request by PaolaHenriquez**
What we did (Adrian and I):
Check and print if it is alive
Set the safety
Set the expiration
basically what issue #102 said to do

### CODE REVIEW

**Comment by WardBenjamin** [comment]
Whoa. Why did every single commit from the master branch get copied over? Is it just me or does the pull request look like this to others as well?

**Comment by PaolaHenriquez** [comment]
No you're right, I must've have done something stupid. If it's a major problem, is there a way to fix it? @WardBenjamin

**Comment by WardBenjamin** [comment]
I actually don't know. @ZackAlfakir is there a way to fix this?

**Comment by PaolaHenriquez** [comment]
I can make a new pull request so that this doesn't appear @WardBenjamin

**Comment by WardBenjamin** [comment]
If you can be sure that this will not occur again, go for it.

**Pull request closed without merging**
