### PR TITLE
Feature joystick

### PR DESCRIPTION
**Pull request by Alexbay218**
please check for errors. (In SmoothJoystick.cpp)
GetY() and GetX() show errors.
So does joystick = new Joystick(1);.
.
.
.
GetValue() can be used to get value of an joystick (Run InitJoystick() first).
X axis = 0, y axis = 1
left hand = 0, right hand = 1

### CODE REVIEW

**Comment by CarlyAmar** [comment]
Joystick == gamepad in this situation. change so that statement fits.

**Comment by Alexbay218** [comment]
It compiles!
.
.
(mwahahahah!)

**Comment by CarlyAmar** [comment]
Can you put setting and ports into robotmap.h and then make Value a variable in the function rather than the class (also, make it lowercase)

**Comment by CarlyAmar** [comment]
I made modifications to it and merged it in a different PR

**Pull request closed without merging**
