### PR TITLE
Merged ports.h into RobotMap.h, which serves the same purpose. Fulfills #55

### PR DESCRIPTION
**Pull request by WardBenjamin**

### CODE REVIEW

**Comment by WardBenjamin** [comment]
This PR fulfills https://github.com/Chantilly612Code/612-2015/issues/55.

**Comment by CharlesCDietzel** [comment]
Actually, this PR is not necessary, because Ahmad and I made the exact same changes in the MecanumDrivetrain commit. Thus, if both are merged, it will conflict and cause problems.

**Comment by toastertaster** [comment]
If it's not needed, then you need to close the associated issue also with a comment.

**Comment by CharlesCDietzel** [comment]
Ok, I have closed the issue. I will now close this PR, unless someone objects.

**Pull request closed without merging**
